# Generated by Django 4.0.2 on 2022-02-11 18:12

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_alter_job_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='description',
            field=markdownx.models.MarkdownxField(blank=True),
        ),
    ]
